package Principal;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * @author Fernando Ariel Acevedo Ejercicio extra 2 de la guia 2 interface
 * Grafica Gestion de Contactos
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Main mainFrame;
    /**
     * Crea un modelo estandar con el cual se cargan las cabeceras y los datos a
     * la JTable
     */
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
        //acomoda el tipo dato que va a tener cada celda. al definirla como boolean
        //se convierte en una casilla de verificacion(CheckBox)
        Class[] types = new Class[]{
            java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
        };

        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }
    };
   

    /**
     * Sobreescribe el metodo getIconImage para poder cargar el icono en la
     * barra de titulo despues se selecciona de las propiedades del JFrame.-
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("recursos/IconoPrincipal.png"));

        return retValue;
    }
    //crea una Linked list para permitir organizar los datos;
    public LinkedList<Contacto> listaContactos = new LinkedList();

    public Main() {
        
        initComponents();
        setTitle("Contactos");       //coloca el titulo de la ventana
        cargarCabecera();
        organizaCabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPrincipal = new javax.swing.JTable();
        jbAgregar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        jtbPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbPrincipal);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");

        jbEditar.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbEliminar)
                    .addComponent(jbEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        
        Carga nuevo = new Carga(this, rootPaneCheckingEnabled, mainFrame);
        nuevo.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_jbAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JTable jtbPrincipal;
    // End of variables declaration//GEN-END:variables
    /**
     * Carga los nombres de la cabecera de la JTable
     *
     */
    private void cargarCabecera() {
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("telefono");
        modelo.addColumn("Correo Electronico");
        jtbPrincipal.setModel(modelo);
    }

    /**
     * metodo para que se pueda organizar la tabla de acuerdo al contenido.
     */
    public void organizaCabecera() {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jtbPrincipal.setRowSorter(sorter);
    }

    public void actualizaLista() {
        for (Contacto contacto : listaContactos) {
            modelo.addRow(new Object[]{
                contacto.getNombre(),
                contacto.getApellido(),
                contacto.getNumero(),
                contacto.geteMail()
            });
        }
    }

    public void cargaDato(Contacto contacto) {
        listaContactos.add(contacto);
        modelo.addRow(new Object[]{
            contacto.getNombre(),
            contacto.getApellido(),
            contacto.getNumero(),
            contacto.geteMail()
        });
    }
}
